config/routes.rb
Paytheartist::Application.routes.draw do

  root :to => 'controller#index'

  get "/welcome" => "controller#welcome"

  resources :splits

 

  

end

app/models/amount.rb
class Amount < ActiveRecord::Base
	belongs_to :artist
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	belongs_to :split
	has_many :amounts, :dependent => :destroy
	accepts_nested_attributes_for :amounts, :allow_destroy => true
end

app/models/split.rb
class Split < ActiveRecord::Base
	has_many :artists
	accepts_nested_attributes_for :artists, :allow_destroy => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/controller_controller.rb
class ControllerController < ApplicationController
  
  def index
  end

  def welcome
  end
end

app/controllers/splits_controller.rb
class SplitsController < ApplicationController
  before_action :set_split, only: [:show, :edit, :update, :destroy]

  # GET /splits
  # GET /splits.json
  def index
    @splits = Split.all
  end

  # GET /splits/1
  # GET /splits/1.json
  def show
  end

  # GET /splits/new
  def new
    @split = Split.new
    3.times do 
      @artist = @split.artists.build
      @artist.amounts.build
    end
  end

  # GET /splits/1/edit
  def edit
  end

  # POST /splits
  # POST /splits.json
  def create
    @split = Split.new(split_params)
    @split.artists.each do |a|
      a.amounts.each do |p|
        p.amount = (p.percent / 100.0) * @split.total
      end
    end

    respond_to do |format|
      if @split.save
        format.html { redirect_to @split, notice: 'Split was successfully created.' }
        format.json { render action: 'show', status: :created, location: @split }
      else
        format.html { render action: 'new' }
        format.json { render json: @split.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /splits/1
  # PATCH/PUT /splits/1.json
  def update
    respond_to do |format|
      if @split.update(split_params)
        format.html { redirect_to @split, notice: 'Split was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @split.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /splits/1
  # DELETE /splits/1.json
  def destroy
    @split.destroy
    respond_to do |format|
      format.html { redirect_to splits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_split
      @split = Split.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def split_params
      params.require(:split).permit(:total, artists_attributes: [:split_id, :name, :id, amounts_attributes: [:percent, :artist_id, :id]] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  ## Thank you, RailsCasts
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, [new_object], :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end

    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end

end

app/helpers/controller_helper.rb
module ControllerHelper
end

app/helpers/splits_helper.rb
module SplitsHelper
end

app/views/controller/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8" />
		<title>Pay The Artist</title>
        <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'></script>
        <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>      
      <!--  <script src='../app/assets/javascripts/bootstrap.js'></script> 
        <script type="text/javascript" charset="utf-8" src='../app/assets/javascripts/bootstrap-modal.js'></script>
       -->
       <script src='http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js'></script>
       <script type="text/javascript">

		var totalAmount = jQuery("#total").val();
		var artists = new Array("artist1");
		var percents = new Array("amount1");
		var amounts = new Array(0);

		function addArtist() {
		  input = jQuery('<p>Artist '+(artists.length+1)+':  <input type = "text" name = "artist'+(artists.length+1)+'"/></p><p>Percent: <input type = "number" name = "amount'+(artists.length+1)+'" value = "0"/>%</p><p id = "splitAmount'+(artists.length+1)+'">Amount: $<span id="fill'+(artists.length+1)+'"></span></p><br/><br/>');
		  console.log("addArtist was run");
		  jQuery('#artists').append(input);
		  artists[artists.length] = "artist" + (artists.length + 1);  
		};

		function updateValues() {
		  console.log("updateValues run");
		  var percentTotal = 0;
		  for (i = 1; i <= artists.length; i++) {
		    var percentTotal = percentTotal + parseFloat($("input[name=amount"+i+"]").val());
		    artists[i-1] = $("input[name=artist"+i+"]").val();
		    percents[i-1] = $("input[name=amount"+i+"]");
		  }
		  if (percentTotal != 100 && artists.length != 1) {
		    alert("Your percentages don't add up to 100!");
		    return false;
		  } else if (parseInt(percentTotal) === 100) {
		    
		    for (i = 1; i <= artists.length; i++) {
		      amounts[i-1] = Math.round((parseFloat($("input[name=amount"+i+"]").val()) / 100 * parseFloat($("#total").val()))*100)/100.0;
		    }
		  }
		  for (i = 1; i <= artists.length; i++) {
		    $("#fill"+i).text(amounts[i-1]);
		  }  
		}; 
		
	</script>
    </head>
    <body>
        <div id="wrapper">
            <header>
                <hgroup>
                     <!--<%= image_tag("RobinTunes.png") %>-->
                    <h1 class="home">
                        <span>
                            <a rel="bookmark" href="/">Pay The Artist</a>
                        </span>
                    </h1>
                    <h2>
                        <span class="headerbar">
                            <span id="About-header" class="headerlink">
                                <a data-toggle="modal" href="#about" role="button">About us</a>
                            </span>
                            <span id="FAQ-header" class="headerlink">
                                <a data-toggle="modal" href="#faq">FAQ</a>
                            </span>
                             <span id="Contact-header" class="headerlink">
                                <a data-toggle="modal" href="#contact">Contact</a>
                            </span>
                             <span id="Legal-header" class="headerlink">
                                <a data-toggle="modal" href="#legal">Legal</a>
                            </span>
                            <span id="Login-header" class="headerlink">
                                <a data-toggle="modal" href="#login">Login</a>
                            </span>
                        </span>
                    </h2>
                    <!--<div id="about-content">This material will be contained in the about</div>-->
                </hgroup>
            </header>
            <div id="main" class="application">
	            <!--<h1>
	                <div class="apptext">Application Space</div>
	                    <div class="appbox"><img src="http://placehold.it/700x500"></div>
	            </h1>-->
	            
	            <div style="float: right; padding-right: 10px">
	            	<input type = "text" id = "artist_search" value="Artist Search" />
	            </div>

                <div  id="form-box">
                    <form>
                        <p>
                            Total you want to pay 
                            <span class='appfield'>
                                <input type = "number" id = "total" value="0" /><br/>
                            </span>
                        </p>
                        <div id = "artists">
                            <p>Artist 1:  
                                <span class='appfield'>
                                    <input type = "text" name = "artist1"/>
                                </span>
                            </p> 
                            <p>Percent: 
                                <span class='appfield'>
                                    <input type = "number" name = "amount1" value = "0"/>
                                </span>
                           </p>
                            <p id = "splitAmount1" > <!-- style = "float: left" --> Amount: $<span id="fill1"></span></p> <br/> <br/>
                        </div>
                        <div style = "clear: both;">
                            <button onClick ="addArtist()" type="button">Add Artist</button>
                            <button onClick = "updateValues()" type = "button">Update Values</button>
                        </div>
                    </form>
                </div>


	<div id="about" class="modal hide fade in" style="display: none; ">  
		<div class="modal-header">  
			<a class="close" data-dismiss="modal">×</a>  
			<h3>About Us</h3>  
		</div>  
		<div class="modal-body">  
			<p>We are a group of students at Rensselaer Polytechnic Institute, who simply believe that most artists don't make enough money for their creations. Our team includes mostly students majoring in computer science or technology related fields. With our technical backgrounds we set out to create a site that would allow direct donation to artists. This project has been in development since fall 2013.</p>                
		</div>  
		<div class="modal-footer">  
			<a href="#" class="btn btn-success" data-dismiss="modal">Close</a>  
		</div>  
	</div>  
	
	<div id="faq" class="modal hide fade in" style="display: none; ">  
		<div class="modal-header">  
			<a class="close" data-dismiss="modal">×</a>  
			<h3>Frequently Asked Questions</h3>  
		</div>  
		<div class="modal-body">  
			<p style="font-weight: bold">How do you know we will distribute all the funds to artists</p>    
			<p>We are a non-profit, university backed, open source, organization interested only in helping out artists. We take no funding for ourselves. We pay for server costs with funding from <a href="http://rcos.rpi.edu/" target="_blank">RCOS</a></p>  
			<p style="font-weight: bold"> What happens if we can't contact the artist or they won't accept donations? </p>    
			<p> After a preset time, all funding not accepted by artists is donated to the charity <a href="http://www.fendermusicfoundation.org" target=" blank">fender music foundation</a> so that no matter what, your donations make a difference.</p>      
		</div>  
		<div class="modal-footer">  
			<a href="#" class="btn btn-success" data-dismiss="modal">Close</a>  
		</div>  
	</div>  
	
	<div id="contact" class="modal hide fade in" style="display: none; ">  
		<div class="modal-header">  
			<a class="close" data-dismiss="modal">×</a>  
			<h3>Contact Us</h3>  
		</div>  
		<div class="modal-body">  
			<p>Jacob Martin - <a href="mailto:martij24@rpi.edu">martij24@rpi.edu</a></p>                
		</div>  
		<div class="modal-footer">  
			<a href="#" class="btn btn-success" data-dismiss="modal">Close</a>  
		</div>  
	</div>  

	<div id="legal" class="modal hide fade in" style="display: none; ">  
		<div class="modal-header">  
			<a class="close" data-dismiss="modal">×</a>  
			<h3>Legal</h3>  
		</div>  
		<div class="modal-body">  
			<p> to be written </p>                
		</div>  
		<div class="modal-footer">  
			<a href="#" class="btn btn-success" data-dismiss="modal">Close</a>  
		</div>  
	</div>  
	
	<div id="login" class="modal hide fade in" style="display: none; ">  
		<div class="modal-header">  
			<a class="close" data-dismiss="modal">×</a>  
			<h3>Login</h3>  
		</div>  
		<div class="modal-body">  
			<p><input type = "text" id = "username" value="Username" /></p>  
			<p><input type = "text" id = "password" value="Password" /></p>              
		</div>  
		<div class="modal-footer">  
			<a href="#" class="btn btn-success" data-dismiss="modal">Close</a>  
		</div>  
	</div>  
            </div>
            <footer>
                <span class="footer_section">
                    <p>Mentor</p>
                    <p>I Forgot</p>
                </span>
                <span class="footer_section">
                    <p>Web Designer</p>
                    <p>Andrew Morris</p>
                </span>
                <span class="footer_section">
                    <p>Backend Masters</p>
                    <p>Jacob Martin</p>
                    <p>Brian Kelley</p>
                </span>
                <span class="footer_section">
                    <p>Copyright &copy; 2013 by us</p>
                </span>
                <%= image_tag("twitter.png", :id => "twitter") %>
                <%= image_tag("facebook.png", :id => "facebook") %>
                <%= image_tag("rss.png", :id => "rss") %>
            </footer>
        </div>
	<script>
	  $(document).ready(function() {
    $("#example").modal();
  });
	</script>        
    </body>
</html>

app/views/controller/welcome.html.erb
<h1>Controller#welcome</h1>
<p>Find me in app/views/controller/welcome.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paytheartist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/splits/_amount_fields.html.erb
<%= f.label :percent %>
<%= f.text_field :percent %>

app/views/splits/_artist_fields.html.erb
<p class = "fields">
	<%= f.label :name, "Artist Name" %>
	<%= f.text_field :name %>

	<%= f.fields_for :amounts do |builder| %>
		<%= render 'amount_fields', :f => builder %>
	<% end %>
	
	<%= f.hidden_field :_destroy %><br/>
	<%= link_to_function "Remove Artist", "remove_fields(this)" %>
	<br/>
	<br/>
</p>

app/views/splits/_form.html.erb
<%= form_for(@split) do |f| %>
  <% if @split.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@split.errors.count, "error") %> prohibited this split from being saved:</h2>

      <ul>
      <% @split.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :total %>
    <%= f.text_field :total %>
  </div>
  <div class = "contain">
    <%= f.fields_for :artists do |builder| %>
      <%= render 'artist_fields', :f => builder %>
    <% end %>

    <%= link_to_add_fields "Add Artist", f, :artists %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/splits/edit.html.erb
<h1>Editing split</h1>

<%= render 'form' %>

<%= link_to 'Show', @split %> |
<%= link_to 'Back', splits_path %>

app/views/splits/index.html.erb
<h1>Listing splits</h1>

<table>
  <thead>
    <tr>
      <th>Total</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @splits.each do |split| %>
      <tr>
        <td><%= split.total %></td>
        <td><%= link_to 'Show', split %></td>
        <td><%= link_to 'Edit', edit_split_path(split) %></td>
        <td><%= link_to 'Destroy', split, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Split', new_split_path %>

app/views/splits/new.html.erb
<h1>New split</h1>

<%= render 'form' %>

<%= link_to 'Back', splits_path %>

app/views/splits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total:</strong>
  <%= @split.total %>
  <% @split.artists.each do |a| %>
  	<br/>
  	<p><%= a.name %></p>
  	<% a.amounts.each do |p| %>
  		<p><%= p.percent %></p>
  		<p><%= p.amount %></p>
  	<% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_split_path(@split) %> |
<%= link_to 'Back', splits_path %>